workflows:
  build-android:
    name: Build TebakKonyolGame
    max_build_duration: 60
    environment:
      java: 17
      android: sdk
    scripts:
      - name: Membersihkan project
        script: ./gradlew clean
      - name: Build APK release
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - aulidanraja@gmail.com
