workflows:
  build-android:
    name: Build Android App
    max_build_duration: 45
    environment:
      java: 17
    scripts:
      - echo "Menjalankan build Android..."
      - echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
