workflows:
  build-android:
    name: Build Android App
    max_build_duration: 15
    environment:
      vars:
        ANDROID_HOME: /opt/android-sdk-linux
    scripts:
      - echo "Menjalankan build Android..."
      - chmod +x ./gradlew
      - ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
