workflows:
  android-workflow:
    name: Build Tebak Garing
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.isRey.tebakkonyol"
      java: 17
      android: sdk
    scripts:
      - name: Clean project
        script: ./gradlew clean
      - name: Build APK
        script: ./gradlew assembleRelease
      - name: Run tests
        script: ./gradlew test
    artifacts:
      - build/app/outputs/**/*.apk
      - build/app/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - aulidanraja@gmail.com
