workflows:
  build-android:
    name: Build Android App
    max_build_duration: 15
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk
    scripts:
      - echo "Menjalankan build Android..."
      - ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
